version: '3.7'

services:
  cat-pics:
    container_name: cat-pics
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:8080
    environment:
      - CHOKIDAR_USEPOLLING=true
